/**
 * JSONL Record Type Definitions
 *
 * Defines the TypeScript interface hierarchy for Claude JSONL session log records.
 * These are the actual record types emitted by Claude Code into
 * ~/.claude/projects/<project-hash>/<session-id>.jsonl
 *
 * IMPORTANT: This is NOT a public Anthropic API and the format may change between
 * versions. All field access uses optional chaining for defensive parsing.
 *
 * Record types:
 *   - 'assistant'            : Claude API response with token usage and tool calls
 *   - 'user'                 : User message or tool results
 *   - 'progress'             : MCP/hook tool timing progress events
 *   - 'file-history-snapshot': File state snapshots (skip for analytics)
 */

// ---------------------------------------------------------------------------
// Base
// ---------------------------------------------------------------------------

/**
 * Common fields present on every JSONL record regardless of type.
 * All fields are optional to account for format evolution across Claude versions.
 */
export interface JSONLRecordBase {
  /** Discriminator, determines which sub-interface to use. */
  type: 'assistant' | 'user' | 'progress' | 'file-history-snapshot';
  /** Session UUID, matches the JSONL filename without extension. */
  sessionId?: string;
  /** Record UUID, unique identifier for this record. */
  uuid?: string;
  /** UUID of the parent record in the conversation tree, or null for root. */
  parentUuid?: string | null;
  /** ISO 8601 timestamp when this record was created. */
  timestamp?: string;
  /** Working directory at time of record creation. */
  cwd?: string;
  /** Claude Code version string. */
  version?: string;
  /** Git branch active when this record was created. */
  gitBranch?: string;
}

// ---------------------------------------------------------------------------
// Content block types (embedded in assistant.message.content)
// ---------------------------------------------------------------------------

/** Thinking block, extended reasoning output. */
export interface ThinkingBlock {
  type: 'thinking';
  /** The raw thinking text produced by Claude. */
  thinking?: string;
}

/** Text block, normal text response. */
export interface TextBlock {
  type: 'text';
  /** The text content of the block. */
  text?: string;
}

/** Tool use block, Claude calling a tool. */
export interface ToolUseBlock {
  type: 'tool_use';
  /** Tool call identifier, referenced by tool_result blocks in the next user record. */
  id?: string;
  /** Tool name (e.g. 'precision_read', 'Task', 'Bash'). */
  name?: string;
  /** Tool input parameters as a JSON-serializable object. */
  input?: Record<string, unknown>;
}

/** Union of all assistant message content block types. */
export type ContentBlock = ThinkingBlock | TextBlock | ToolUseBlock;

// ---------------------------------------------------------------------------
// Tool result types (embedded in user.message.content)
// ---------------------------------------------------------------------------

/**
 * Tool result block, returned by a tool invocation.
 * Appears in user records that follow assistant tool_use records.
 */
export interface ToolResultBlock {
  /** Matches the id field from the corresponding tool_use block. */
  tool_use_id?: string;
  type: 'tool_result';
  /** Tool result content, may be a plain string or an array of typed content objects. */
  content?: string | unknown[];
  /** Whether the tool call produced an error. */
  is_error?: boolean;
}

// ---------------------------------------------------------------------------
// Usage / cost types
// ---------------------------------------------------------------------------

/**
 * Token usage breakdown from a Claude API response.
 * All numeric fields may be absent on older JSONL entries.
 */
export interface AssistantUsage {
  /** Input tokens sent to the API (not counting cache reads). */
  input_tokens?: number;
  /** Output tokens generated by the API. */
  output_tokens?: number;
  /** Tokens written into the context cache (prompt caching write). */
  cache_creation_input_tokens?: number;
  /** Tokens read from the context cache (prompt caching read, cheaper). */
  cache_read_input_tokens?: number;
  /** Extended cache creation breakdown. */
  cache_creation?: {
    /** Tokens cached for 5-minute TTL. */
    ephemeral_5m_input_tokens?: number;
    /** Tokens cached for 1-hour TTL. */
    ephemeral_1h_input_tokens?: number;
  };
}

// ---------------------------------------------------------------------------
// Specific record types
// ---------------------------------------------------------------------------

/**
 * Assistant turn record, the primary data source for API token usage.
 *
 * Contains:
 *   - Full token usage breakdown (input, output, cache read/write)
 *   - Array of content blocks (text, thinking, and tool_use calls)
 *   - Model identifier and stop reason
 *
 * NOTE: cost_usd is NOT present, must be calculated from token counts + config rates.
 */
export interface JSONLAssistantRecord extends JSONLRecordBase {
  type: 'assistant';
  message?: {
    /** Claude model identifier (e.g. 'claude-opus-4-6'). */
    model?: string;
    /** Token usage breakdown for this API call. */
    usage?: AssistantUsage;
    /**
     * Content blocks, may include thinking, text, and tool_use entries.
     * Array order matches Claude's output order.
     */
    content?: ContentBlock[];
    /** API stop reason (e.g. 'end_turn', 'tool_use', 'max_tokens'). */
    stop_reason?: string;
  };
  /** Unique identifier for this API request (from Anthropic). */
  requestId?: string;
}

/**
 * User turn record, human message or tool results.
 *
 * content is either:
 *   - A plain string (human message)
 *   - An array of ToolResultBlock objects (tool responses)
 */
export interface JSONLUserRecord extends JSONLRecordBase {
  type: 'user';
  message?: {
    role?: 'user';
    /** Human message string OR array of tool result blocks. */
    content?: string | ToolResultBlock[];
  };
}

/**
 * Progress record, MCP server or hook tool timing events.
 *
 * These arrive in pairs:
 *   - status='started'   when the tool begins executing
 *   - status='completed' when the tool finishes (includes elapsedTimeMs)
 *
 * Used for precision tool performance tracking.
 */
export interface JSONLProgressRecord extends JSONLRecordBase {
  type: 'progress';
  data?: {
    /** Distinguishes MCP server events from hook events. */
    type?: 'hook_progress' | 'mcp_progress';
    /** 'started' or 'completed'. elapsedTimeMs only present on 'completed'. */
    status?: 'started' | 'completed';
    /** MCP server name (e.g. 'plugin:goodvibes:precision-engine'). */
    serverName?: string;
    /** Tool function name (e.g. 'precision_read'). */
    toolName?: string;
    /** Total elapsed milliseconds, only present when status='completed'. */
    elapsedTimeMs?: number;
  };
  /** Matches the tool_use id that triggered this progress event. */
  toolUseID?: string;
}

/**
 * File history snapshot, records file state for undo/redo functionality.
 * These records are large and irrelevant for analytics, skip them.
 */
export interface JSONLFileHistoryRecord extends JSONLRecordBase {
  type: 'file-history-snapshot';
  /** Conversation message ID this snapshot is associated with. */
  messageId?: string;
  snapshot?: {
    /** Map of tracked file paths to their backed-up content hashes. */
    trackedFileBackups?: Record<string, unknown>;
    /** ISO 8601 timestamp of the snapshot. */
    timestamp?: string;
  };
}

/**
 * Discriminated union of all JSONL record types.
 * Use the `type` field to narrow to a specific sub-interface.
 */
export type JSONLRecord =
  | JSONLAssistantRecord
  | JSONLUserRecord
  | JSONLProgressRecord
  | JSONLFileHistoryRecord;

// ---------------------------------------------------------------------------
// Extraction result types
// ---------------------------------------------------------------------------

/**
 * Result of parsing a JSONL file (or a portion of one).
 * Returned by JSONLReader.parseFile().
 */
export interface JSONLParseResult {
  /** Successfully parsed records. */
  records: JSONLRecord[];
  /** Byte offset after the last successfully parsed line (for incremental reads). */
  newOffset: number;
  /** Total number of lines processed (including skipped). */
  linesParsed: number;
  /** Number of lines skipped due to being empty or invalid JSON. */
  linesSkipped: number;
  /** Non-fatal parsing error messages (one per bad line). */
  errors: string[];
}

/**
 * Information about a single tool call, extracted from assistant + user record pairs.
 */
export interface ToolCallInfo {
  /** Tool call ID (from the tool_use block). */
  id: string;
  /** Tool name. */
  name: string;
  /** Tool input parameters. */
  input: Record<string, unknown>;
  /** Session this call belongs to. */
  sessionId: string;
  /** ISO 8601 timestamp of the assistant record containing this call. */
  timestamp: string;
  /** UUID of the assistant record. */
  assistantRecordUuid: string;
  /** Raw tool result content, if a matching user record was found. */
  resultContent?: string | unknown[];
  /** Whether the tool result indicates an error. */
  isError?: boolean;
}

/**
 * Inferred agent activity record.
 * Agents are NOT explicit JSONL record types, they are inferred from
 * assistant records containing tool_use blocks with name === 'Task'.
 */
export interface AgentActivityInfo {
  /** Unique identifier for this agent spawn (the tool_use id). */
  agentId: string;
  /** Session that spawned this agent. */
  parentSessionId: string;
  /** ISO 8601 timestamp of the Task tool_use record. */
  spawnedAt: string;
  /** ISO 8601 timestamp of the tool_result record, if the agent has completed. */
  completedAt?: string;
  /** Task tool input (may contain task description). */
  taskInput: Record<string, unknown>;
  /** Whether the agent has completed (tool_result received). */
  completed: boolean;
  /** Exit code or status from the tool_result, if available. */
  exitStatus?: unknown;
}

/**
 * Session-level summary information extracted from JSONL records.
 */
export interface SessionInfo {
  /** Session UUID (from record sessionId fields). */
  sessionId: string;
  /** Primary model used in this session (from first assistant record). */
  model: string;
  /** ISO 8601 timestamp of the earliest record. */
  startedAt: string;
  /** ISO 8601 timestamp of the latest record. */
  lastActivityAt: string;
  /** Working directory from the first record. */
  cwd: string;
  /** Git branch from the first record. */
  gitBranch: string;
  /** Claude Code version. */
  version: string;
}

/**
 * Precision tool timing entry extracted from progress record pairs.
 */
export interface PrecisionToolTiming {
  /** MCP tool call ID that triggered this timing event. */
  toolUseId: string;
  /** MCP server name (e.g. 'plugin:goodvibes:precision-engine'). */
  serverName: string;
  /** Tool function name (e.g. 'precision_read'). */
  toolName: string;
  /** Elapsed milliseconds (from the 'completed' progress record). */
  elapsedTimeMs: number;
  /** Session this timing belongs to. */
  sessionId: string;
  /** ISO 8601 timestamp of the completed event. */
  timestamp: string;
}

