/**
 * PostToolUse Task Hook
 *
 * Fires ONLY when the Task tool completes (agent finishes).
 * Queries the runtime engine for pending directives generated by
 * SubagentStop's agent:completed event, and injects them into the
 * orchestrator's conversation via hookSpecificOutput.additionalContext.
 *
 * Sequence:
 * 1. Agent completes
 * 2. SubagentStop fires → sends agent:completed → runtime generates directive
 * 3. Task tool returns to parent
 * 4. THIS HOOK fires → queries get_directives → drains queue → injects
 * 5. Orchestrator sees agent result + directive
 */

import {
  respond,
  createResponse,
  isTestEnvironment,
  buildGvDirectiveTag,
} from './shared/index.js';
import { RuntimeClient } from './shared/runtime-client.js';
import { stdin } from 'node:process';

export async function runPostToolUseTaskHook(): Promise<void> {
  try {
    // Discard stdin without blocking
    stdin.resume();

    const runtimeClient = new RuntimeClient();

    // Fast path: runtime not available — no IPC overhead
    if (!runtimeClient.isAvailable()) {
      respond(createResponse());
      return;
    }

    // Query runtime for pending directives
    const result = await runtimeClient.query({ kind: 'get_directives' });

    if (result?.kind === 'system_message' && result.message) {
      const additionalContext = buildGvDirectiveTag(result.message);
      respond(createResponse({ additionalContext }));
      return;
    }

    // No directives pending
    respond(createResponse());
  } catch {
    // Never block — silently allow
    respond(createResponse());
  }
}

/* v8 ignore start - test environment guard */
if (!isTestEnvironment()) {
  runPostToolUseTaskHook().catch(() => {
    respond(createResponse());
  });
}
/* v8 ignore stop */
