/**
 * PostToolUse Task Hook — DISABLED
 *
 * This hook is disabled due to a Claude Code bug where PostToolUse hooks
 * with additionalContext do not surface for MCP tool calls:
 * https://github.com/anthropics/claude-code/issues/24788
 *
 * When this bug is fixed, this hook can be re-enabled by:
 * 1. Uncommenting the hooks.json entry (see bottom of this file)
 * 2. Rebuilding the hooks scripts
 *
 * Original purpose:
 * Fires ONLY when the Task tool completes (agent finishes).
 * Queries the runtime engine for pending directives generated by
 * SubagentStop's agent:completed event, and injects them into the
 * orchestrator's conversation via hookSpecificOutput.additionalContext.
 *
 * Sequence:
 * 1. Agent completes
 * 2. SubagentStop fires → sends agent:completed → runtime generates directive
 * 3. Task tool returns to parent
 * 4. THIS HOOK fires → queries get_directives → drains queue → injects
 * 5. Orchestrator sees agent result + directive
 *
 * Current fallback: PreToolUse directive drain hook
 * (pre-tool-use-directive-drain.mjs) handles recovery instead.
 */

import {
  respond,
  createResponse,
  isTestEnvironment,
  buildGvDirectiveTag,
} from './shared/index.js';
import { RuntimeClient } from './shared/runtime-client.js';
import { stdin } from 'node:process';

export async function runPostToolUseTaskHook(): Promise<void> {
  try {
    // Discard stdin without blocking
    stdin.resume();

    const runtimeClient = new RuntimeClient();

    // Fast path: runtime not available — no IPC overhead
    if (!runtimeClient.isAvailable()) {
      respond(createResponse());
      return;
    }

    // Query runtime for pending directives
    const result = await runtimeClient.query({ kind: 'get_directives' });

    if (result?.kind === 'system_message' && result.message) {
      const gvDirective = buildGvDirectiveTag(result.message);
      respond(createResponse({ additionalContext: { gv_directive: gvDirective } }));
      return;
    }

    // No directives pending
    respond(createResponse());
  } catch {
    // Never block — silently allow
    respond(createResponse());
  }
}

/* v8 ignore start - test environment guard */
if (!isTestEnvironment()) {
  runPostToolUseTaskHook().catch(() => {
    respond(createResponse());
  });
}
/* v8 ignore stop */

/*
 * ─── Re-enable instructions ───────────────────────────────────────────────────
 *
 * When https://github.com/anthropics/claude-code/issues/24788 is resolved,
 * add the following entry to hooks.json under "PostToolUse":
 *
 * "PostToolUse": [
 *   {
 *     "matcher": "Task",
 *     "hooks": [
 *       {
 *         "type": "command",
 *         "command": "node \"${CLAUDE_PLUGIN_ROOT}/hooks/scripts/dist/post-tool-use-task.js\"",
 *         "timeout": 5
 *       }
 *     ]
 *   }
 * ]
 *
 * Then rebuild: cd plugins/goodvibes/hooks/scripts && npm run build
 */
